### ISSUE TITLE
VCAN4-4 HSCAN & HSCAN2 tx & rx ISO15765-2 have different manifestation

### ISSUE THREAD

**Issue by eric-qianfeng** [intrepidcs/python_ics#91] opened 2020-12-01 06:57 UTC
When use VCAN4-4 to tx & rx 15765-2 message and found a very weird things. Attached the python code they used, which is based on the demo code. Please remove the txt extenstion.
[iso15765_example.py.txt](https://github.com/intrepidcs/python_ics/files/5620732/iso15765_example.py.txt)

If use network HSCAN1 (netid is ics.NETID_HSCAN), the get_messages function return the messages what we want, it include 0x7E0 & 0x7E8:
![OK](https://user-images.githubusercontent.com/12888069/100707264-5a460e00-33e5-11eb-8276-6f4efee8e39a.jpg)

But if we change the network to HSCAN2(netid is ics.NETID_HSCAN2), the get_messages function return messages doesn’t include 0x7E8:
![NOK](https://user-images.githubusercontent.com/12888069/100707297-6a5ded80-33e5-11eb-88fd-f6e5b604d535.jpg)

We use the same code to test Fire2 HSCAN & HSCAN2, it works, the return messages include 0x7E8.

**Comment by drebbe-intrepid** [comment] 2020-12-07 16:32
@eric-qianfeng Can you provide me with the following:

1. OS version
2. Python version
3. icsneo40.dll version
4. Is this reproducible every time?
5. Hardware setup. It looks like you have two different setups, FIRE2 to FIRE2 and ValueCAN4-4 to ValueCAN4-4?

**Comment by eric-qianfeng** [comment] 2020-12-08 02:43
@drebbe-intrepid , the following is my answer:
1. OS version
    * Windows 10
2. Python version
    * V3.6.8 (32-bit)
3. icsneo40.dll version
    * V3.9.3.17
4. Is this reproducible every time?
    * Yes, it is. 
5. Hardware setup. It looks like you have two different setups, FIRE2 to FIRE2 and ValueCAN4-4 to ValueCAN4-4?
    * Yes, two setups to compare the result. One is ValueCAN4-4 to Fire2, another is Fire2 to Fire2; the other side is always Fire2 to simulate an ECU, and I use VSpy3 to monitor and transmit the flow control.

**Comment by drebbe-intrepid** [comment] 2020-12-11 14:34
I was unable to reproduce this here and I looks like you are in contact with our support department. I'm going to close this out, if you find there is an issue with the API please re-open this issue please!

**Closed by drebbe-intrepid** 2020-12-11 14:34 UTC
Labels: needs more info
